[package]
name = "mdbook-bibfile-referencing"
version = "0.1.0"
authors = ["Jacob Halsey <jacob@jhalsey.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mdbook = "0.4.4"
clap = "3.0.0-beta.2"
pandoc = "0.8.1"
serde = "1.0.118"
serde_json = "1.0.61"

[dev-dependencies]
tempfile = "3"
