[book]
authors = ["Jacob Halsey"]
language = "en"
multilingual = false
src = "src"
title = "test-book"

[preprocessor.bibliography]
command = "cargo run src/bibliography.bib src/ieee.csl --flavour commonmark"